image:
  repository: bitnamilegacy/keycloak

auth:
  adminUser: admin
  existingSecret: keycloak-admin
  passwordSecretKey: password

proxy: edge
production: false

httpRelativePath: /keycloak/
replicaCount: 1

postgresql:
  enabled: false

externalDatabase:
  host: ${db_host}
  port: 5432
  database: keycloakdb
  user: ${db_user}
  existingSecret: keycloak-db
  existingSecretPasswordKey: password

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: ${hostname}
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
